### ISSUE TITLE
pulling private image from gcr fails with 403 forbidden

### ISSUE THREAD

**Issue by laszlocph** [genuinetools/img#106]
Hi Jessie, 

first of all, Img is amazing. Thanks for making it!

I tried few of my images and they consistently fail pulling in images from `gcr.io` with the error bellow:

`failed to solve: httpReaderSeeker: failed open: unexpected status code https://eu.gcr.io/v2/xxx/myimage/blobs/sha256:135ed000cxxxxxxxxxxxxxxxxxxxxxx46c0e33e: 403 Forbidden`

Maybe you or others have seen / solved this already.

Thanks.

**Comment by jessfraz** [comment]
Are these images private?

If they are public can you give me the names and I'll try to repro locally

**Comment by laszlocph** [comment]
They are private. I'll try and repro with public ones.

**Comment by jessfraz** [comment]
ah it might be a problem with auth, I'll try some private ones.

**Comment by jessfraz** [comment]
opened one unified issue for this :) #128
