### ISSUE TITLE
Make the runc binary optional

### ISSUE THREAD

**Issue by mrueg** [genuinetools/img#107]
In distributions (btw. img is now available in gentoo) we usually don't want to bundle binaries but want to specify it as a dependency. Would it be possible to add an option that disables the embedded binary building for runc?

**Comment by jessfraz** [comment]
I can make a build tag I'll place details here when done :) also woohoo Gentoo!

**Comment by frezbo** [comment]
:+1: I would like to build my own runc. :100: to build tag

**Comment by jessfraz** [comment]
opened https://github.com/genuinetools/img/pull/108 :)
