### ISSUE TITLE
Request: tag official images and/or keep old untagged images

### ISSUE THREAD

**Issue by AkihiroSuda** [genuinetools/img#121]
So that I can pin img to a specific version in https://github.com/AkihiroSuda/buildbench

**Comment by jessfraz** [comment]
ah will do! I think this is in the source pull code :)

**Comment by jessfraz** [comment]
updated so it will push tags from now on, the latest is here now: https://r.j3ss.co/repo/img/tags

**Comment by AkihiroSuda** [comment]
Thanks!

**Comment by AkihiroSuda** [comment]
@jessfraz  Could you push 0.4.6?

**Comment by jessfraz** [comment]
done :) sorry
