### ISSUE TITLE
Allow saving to oci format

### ISSUE THREAD

**Issue by knieriem** [genuinetools/img#125]
When using `img save` the resulting tar appears to use `application/vnd.docker.*` media types, rather than `application/vnd.oci.image.*`, and the manifest entry in index.json seems not contain an annotation with an image reference like _latest_. In order to get an image-tar that I can use with `oci-image-tool` or `umoci`, I currently run a little shell script that replaces media types using sed:

    s,application/vnd.docker.image.rootfs.diff.tar.gzip,application/vnd.oci.image.layer.v1.tar+gzip,g
    s,application/vnd.docker.container.image.v1+json,application/vnd.oci.image.config.v1+json,g
    s,application/vnd.docker.distribution.manifest.v2+json,application/vnd.oci.image.manifest.v1+json,g

and that appends a _latest_ reference to the manifest entry in index.json:

     sed 's/}]}/,"annotations":{"org.opencontainers.image.ref.name":"latest"}&/'

After manually adjusting the values of some `digest` and `size` fields, the resulting image-tar gets successfully validated with `oci-image-tool validate`.

As I'm quite new to OCI  -- is there something unusual about my approach to use a `save`d image-tar with tools like oci-image-tool or umoci? Would it be possible to make `img save` insert oci media types and an image reference label, or would this, currently, break some other uses?

**Comment by jessfraz** [comment]
This is working as intended. We have considered adding a --format flag to switch from default docker to oci... Patches welcome

**Comment by knieriem** [comment]
Thanks for the fast response. Btw, what do you think about adding

    --- a/client/save.go
    +++ b/client/save.go
    @@ -46,6 +46,9 @@ func (c *Client) SaveImage(ctx context.Context, image, format string, writer io.
     		}
        	case "oci":
     		exporter = &oci.V1Exporter{}
    +		img.Target.Annotations = map[string]string{
    +			"org.opencontainers.image.ref.name": named.String(),
    +		}
     	default:
     		return fmt.Errorf("%q is not a valid format", format)
     	}

This would address the comment
>   [// It is up to caller to put "org.opencontainers.image.ref.name" annotation to desc.](https://github.com/containerd/containerd/blob/c1e1f3d6d990e79cfc22317558571008536e0f6e/images/oci/exporter.go#L35)

in oci/exporter.go. I'm not sure whether one should use named.String() or just the tag, though. 

Perhaps I'll try to work on the [TODO mentioned in line 37](https://github.com/containerd/containerd/blob/c1e1f3d6d990e79cfc22317558571008536e0f6e/images/oci/exporter.go#L37) of the same file, if time permits.
