### ISSUE TITLE
Request: export container's filesystem

### ISSUE THREAD

**Issue by paulbry** [genuinetools/img#131]
This is an exciting tool. I wanted to submit the idea of a potential enhancement, adding an `img export` option. Currently `save` works but if I wanted a flattened tar archive I do so via additional scripting.
Is there any desire from others or plan to add an `export` option, similar to Docker?

**Comment by jessfraz** [comment]
have you seen https://github.com/genuinetools/img#unpack-an-image-to-a-rootfs

**Comment by jessfraz** [comment]
then you can pipe that to a tar command

**Comment by jessfraz** [comment]
you could also add a save --format flattened, we already have the format flag

**Comment by paulbry** [comment]
Completely missed `unpack`, thanks.
I'll take have to take a closer look.

**Comment by AkihiroSuda** [comment]
Is this closable?
