### ISSUE TITLE
build on arm64

### ISSUE THREAD

**Issue by vielmetti** [genuinetools/img#132]
Build fails on arm64 system (Packet c1.large.arm) Ubuntu 16.04 LTS, using instructions at https://github.com/genuinetools/img/blob/master/README.md#via-go

Perhaps related: #119 

### What I expected

`go get github.com/genuinetools/img` succeeds with no error messages, resulting binary works.

### What I got

```
ed@ed-c1-large-arm:~$ go get github.com/genuinetools/img
# github.com/genuinetools/img/internal/binutils
go/src/github.com/genuinetools/img/internal/binutils/install.go:16:15: undefined: Asset
```

### What might be going wrong

At https://github.com/genuinetools/img/blob/master/internal/binutils/install.go#L12 the comment

> InstallRuncBinary installs the embedded runc binary to the host.

Not clear yet where `runc` is coming from, or whether it's going to pick up an `arm64` version.

### What would also be fine

If there were arm64 binaries built in CI (but that's another issue), or if build from Makefile were to work (that's my next try).

**Comment by vielmetti** [comment]
Build from Makefile works when following this instruction from the README

`make BUILDTAGS="seccomp noembed"`

```
ed@ed-c1-large-arm:~/go/src/github.com/genuinetools/img$ ./img version
img:
 version     : v0.4.6
 git hash    : bcebacf
 go version  : go1.10.2
 go compiler : gc
 platform    : linux/arm64
```

So *something* works.

**Comment by AkihiroSuda** [comment]
duplicate: https://github.com/genuinetools/img/issues/119
