### ISSUE TITLE
feature: --volumes-from as in docker build

### ISSUE THREAD

**Issue by frezbo** [genuinetools/img#137]
This would really improve builds times when we need to use some cache from other image. Not sure if this is valid.

**Comment by jessfraz** [comment]
this isn't a feature in docker so can you give more details please.

**Comment by AkihiroSuda** [comment]
RUN --mount cache should work. (probably after revendoring bk)

**Comment by frezbo** [comment]
@jessfraz yeh you are right, I got messed up with the `--volumes-from` command of `docker run`. (got this idea because `kitchen-dokken` supported that :D). I will gladly close this RFC.

@AkihiroSuda  can you look at https://github.com/genuinetools/img/issues/136, that's exactly what I did.
