### ISSUE TITLE
copy file range not permitted

### ISSUE THREAD

**Issue by MarcoSchaar** [genuinetools/img#157]
Hi
while testing an error occurred 

#8 0.109 panic: failed to copy /src-0/htdocs/. to usr/local/apache2/: failed to copy files: copy file range failed: operation not permitted
#8 0.109
#8 0.109 goroutine 1 [running]:
#8 0.109 main.main()
#8 0.109        /go/src/github.com/tonistiigi/copy/cmd/copy/main.go:57 +0x2af

**Comment by tonistiigi** [comment]
@MarcoSchaar What os/arch was this on? See https://github.com/containerd/continuity/issues/135 https://github.com/tonistiigi/fsutil/pull/50

**Comment by MarcoSchaar** [comment]
Hi @tonistiigi it is redhat 7

**Comment by tonistiigi** [comment]
The error is handled in newer versions of the copy image `tonistiigi/copy:v0.1.7`+

**Comment by AkihiroSuda** [comment]
Is this closable now?

**Comment by MarcoSchaar** [comment]
forgot to close
thanks a lot
