### ISSUE TITLE
ECR Login Error

### ISSUE THREAD

**Issue by infinitydon** [genuinetools/img#183]
Hi,

I tried to login to AWS ECR but I got the following error using basic auth:

```
img login https://xxxx.dkr.ecr.eu-central-1.amazonaws.com
Username: 
Password:
creating registry client failed: Get https://xxx.ecr.eu-central-1.amazonaws.com/v2/: basic auth required
```

```
img version
img:
 version     : v0.5.1
 git hash    : 671aaaa
 go version  : go1.10.4
 go compiler : gc
 platform    : linux/amd64

```

Also I don't think **img** supports using AWS token for login **_(aws ecr get-login --no-include-email --region eu-central-1)_**?

**Comment by rodriguezsergio** [comment]
Login and `img pull` works for me, but I can't push. Did you replace `docker login` with `img login` once you did `ecr get-login` ?

**Comment by kekoav** [comment]
@infinitydon  ECR works fine when using `aws ecr get-login`, then replacing `docker` with `img. A symlink from `img` to `docker` also works.

This should be closed @AkihiroSuda .
