### ISSUE TITLE
Docker run: newuidmap: open of uid_map failed: Permission denied

### ISSUE THREAD

**Issue by Asmayra** [genuinetools/img#191]
Hey, I'm trying to run img in docker on Ubuntu 18.04 and I'm getting the following error:

```
$ docker run --rm -it --name img --volume $(pwd):/home/user/src:ro --workdir /home/user/src --volume "${HOME}/.docker:/root/.docker:ro" --privileged r.j3ss.co/img build -t user/myimage .
newuidmap: open of uid_map failed: Permission denied
nsenter: failed to use newuidmap: Invalid argument
nsenter: failed to sync with parent: SYNC_USERMAP_ACK: got 255: Invalid argument
```
Any advise?

**Comment by brad-jones** [comment]
So if I go back to v0.5.1 this error no longer occurs.

**Comment by AkihiroSuda** [comment]
I confirmed I can hit this issue with Ubuntu 18.04 kernel `4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018`.

The issue should be related to https://github.com/genuinetools/img/pull/184, but I think the PR had been working on Ubuntu 18.04 at that time..

cc @giuseppe

**Comment by AkihiroSuda** [comment]
https://github.com/genuinetools/img/blob/7c58387804c0897b7086ee745c4ea528b4b40509/Dockerfile#L37

Downgrading shadow from shadow-maint/shadow@42324e501768675993235e03f7e4569135802d18 to shadow-maint/shadow@bb3f810611ca254b07f0af4597b2735b6d1c4be1 works for me.

Seems regression in shadow-maint/shadow@52c081b02c4ca4432330ee336a60f6f803431e63 (https://github.com/shadow-maint/shadow/pull/138)

cc @brauner @hallyn

**Comment by AkihiroSuda** [comment]
A weird thing is that `moby/buildkit:v0.3.2-rootless` does not seem to hit the issue, even thought it uses https://github.com/shadow-maint/shadow/commit/42324e501768675993235e03f7e4569135802d18 as well.

https://github.com/moby/buildkit/blob/fba893e789edf99105ca215e8ff6e8c46829daf2/hack/dockerfiles/test.buildkit.Dockerfile#L216

**Comment by AkihiroSuda** [comment]
@giuseppe Thanks, your patch works for me with the latest img. Although I'm still curious why BuildKit/RootlessKit did not hit the issue...

**Comment by giuseppe** [comment]
> Although I'm still curious why BuildKit/RootlessKit did not hit the issue...

were you running the container without `CAP_SYS_ADMIN`?

**Comment by AkihiroSuda** [comment]
Sorry rootlesskit hits the issue as well, it  looks like `moby/buildkit:v0.3.2-rootless` just uses different version of pre-built newuidmap binary, so `moby/buildkit:v0.3.2-rootless` is free from the issue.

**Comment by jeunii** [comment]
I have a question regarding a similar issue. When you guys say

> Ensured uidmap & libseccomp-dev packages have been installed.
> /proc/sys/kernel/unprivileged_userns_clone is also enabled.

Are we talking about the host OS ? In my case I am deploying my docker image on my MacOS.

Eventually I plan to run my builds in GKE. So is the assumption correct that my kubernetes node's OS should have the above settings ? So that the `img` container can run on them ?

**Comment by AkihiroSuda** [comment]
The host os.

GKE COS is broken but GKE Ubuntu works.

**Comment by jeunii** [comment]
@AkihiroSuda Thank you for the reply. Could you kindly elaborate a bit on the details why COS is incompatible with `img`. Im making a study on the feasibility of using `img` in our GKE managed k8s and all our build nodes use COS as the Image type. 

Does it have to do with  `user namespace support enabled`. Does COS based systems not support that ?

**Comment by AkihiroSuda** [comment]
COS has a kernel patch issue https://github.com/moby/buildkit/issues/879
