### ISSUE TITLE
Make git a dependency optional

### ISSUE THREAD

**Issue by hoshsadiq** [genuinetools/img#195]
Just tried this out as I'm trying to build a VM with minimal dependencies with runc and containerd et al (i.e. without docker).

While trying to run img to build an image, it failed due to git not being installed. Is there a reason for git being a requirement?

```
# img build -t x11 .
Building docker.io/library/test:latest
Setting up the rootfs... this may take a bit.
[+] Building 0.0s (0/0)
creating worker failed: failed to find git binary: exec: "git": executable file not found in $PATH
```

Would be nice to make this optional.

**Comment by nogoegst** [comment]
AFAIK buildkit itself depends on `git` binary.

**Comment by AkihiroSuda** [comment]
PR: https://github.com/moby/buildkit/pull/737

**Comment by hoshsadiq** [comment]
Can this be closed now that buildkit has it merged?

**Comment by AkihiroSuda** [comment]
Not vendored yet

**Comment by AkihiroSuda** [comment]
closing via #221
