### ISSUE TITLE
Port over `docker build --secret` and `docker build --ssh` (low hanging fruit)

### ISSUE THREAD

**Issue by AkihiroSuda** [genuinetools/img#198]

**Comment by bryanhuntesl** [comment]
This would be _really_ useful - it's so hard to build code from private repositories using Docker.

**Comment by tlawrie** [comment]
Any update on when this may be implemented?

**Comment by morganchristiansson** [comment]
Any workarounds? Not having a lot of luck on google searching for img sshagent

**Comment by AkihiroSuda** [comment]
img project is not under active development recently.
I'd suggest using `buildctl-daemonless.sh build --ssh` instead.

https://github.com/moby/buildkit/blob/master/examples/buildctl-daemonless/buildctl-daemonless.sh
