### ISSUE TITLE
Add --cache-from

### ISSUE THREAD

**Issue by grayhemp** [genuinetools/img#205]
It would be nice to have it (see --cache-from here https://docs.docker.com/engine/reference/commandline/build/) for cache pre-population.

**Comment by AkihiroSuda** [comment]
this one would need https://github.com/moby/buildkit/issues/752

**Comment by Chippiewill** [comment]
@AkihiroSuda You marked this as "beginner" I've had a go at doing this based on orisano's original MR but I'm not 100% sure what's required.

So far I've set `export-cache` to inline for the original image to be cached from and plumbed in the `cache-from` flag but buildkit is unhappy about importing the cache manifest:

`ERROR importing cache manifest from <image tag>`

**Comment by yangm97** [comment]
@Chippiewill I guess it's because cache images != output images. 

https://github.com/moby/buildkit/blob/master/README.md#exportingimporting-build-cache-not-image-itself

**Comment by taxilian** [comment]
I think this can be closed, since it's implemented?
