### ISSUE TITLE
Missing --insecure-registry flag for "login" command

### ISSUE THREAD

**Issue by isikemre** [genuinetools/img#278]
There is already a PR for this and someone already created this flag for the `push` command, but the login command needs it too.
Because I cannot login into my insecure local registry it says `x509: certificate signed by unknown authority`.

The PR I mentioned above is: https://github.com/genuinetools/img/pull/258

I hope this PR gets into the code 👍

**Comment by kekoav** [comment]
@isikemre if you do in fact have a self-signed certificate, you can add that to your ca-certificate store in Linux.

**Comment by isikemre** [comment]
@kekoav Yeah, I already did that, but that feature for `img` would be nice, too.
We can close this issue, thx!
