### ISSUE TITLE
Package moved to community in Alpine Linux

### ISSUE THREAD

**Issue by oxr463** [genuinetools/img#292]
This will change the location to the following:

```sh
apk add img --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
```

Source: https://github.com/genuinetools/img/blob/master/README.md#alpine-linux

Also, this means `img` will appear in the next tagged release of Alpine. Once that happens, we can drop the `--repository` flag.

**Comment by oxr463** [comment]
See: https://pkgs.alpinelinux.org/package/v3.12/community/x86_64/img

**Comment by tlawrie** [comment]
Hi @oxr463 is there going to be an updated package. 5.10 is from May but there seems to be newer code.

**Comment by oxr463** [comment]
@tlawrie see: https://github.com/genuinetools/img/issues/309#issuecomment-724426149

**Comment by oxr463** [comment]
Package has been upgraded to 0.5.11 for Alpine, (See: https://pkgs.alpinelinux.org/package/edge/community/x86_64/img).
