### ISSUE TITLE
Binary fails with segmentation fault

### ISSUE THREAD

**Issue by apapsch** [genuinetools/img#302]
I downloaded your binary 0.5.10, checksum matches. It crashes on Fedora 32 Workstation. Building from source seems to be alright (I got the help displayed).

```
$ ./img-linux-amd64 -h
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fa71c27c7cb]

runtime stack:
runtime.throw(0x116b440, 0x2a)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/runtime/signal_unix.go:378 +0x47c

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xdea640, 0xc0001dbb90, 0xc0000d0948)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/runtime/cgocall.go:128 +0x5b fp=0xc0001dbb60 sp=0xc0001dbb28 pc=0x403d0b
os/user._Cfunc_mygetpwnam_r(0xc0003a17a0, 0xc0004165a0, 0x403e060, 0x400, 0xc0000d0948, 0x0)
        _cgo_gotypes.go:156 +0x4d fp=0xc0001dbb90 sp=0xc0001dbb60 pc=0x5026fd
os/user.lookupUser.func1.1(0xc0003a17a0, 0x7, 0x7, 0xc0004165a0, 0xc00043cc30, 0xc0000d0948, 0xc0001dbc40)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/os/user/cgo_lookup_unix.go:70 +0x15f fp=0xc0001dbbe0 sp=0xc0001dbb90 pc=0x50469f
os/user.lookupUser.func1(0x102e7e0)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/os/user/cgo_lookup_unix.go:70 +0x57 fp=0xc0001dbc28 sp=0xc0001dbbe0 pc=0x504747
os/user.retryWithBuffer(0xc00043cc30, 0xc0001dbd48, 0x6, 0xc0003a17a0)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/os/user/cgo_lookup_unix.go:251 +0x3b fp=0xc0001dbc80 sp=0xc0001dbc28 pc=0x503c0b
os/user.lookupUser(0x11418cd, 0x6, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/os/user/cgo_lookup_unix.go:61 +0x1c9 fp=0xc0001dbd90 sp=0xc0001dbc80 pc=0x502cb9
os/user.Lookup(0x11418cd, 0x6, 0xc561c2, 0xc000416540, 0xc0001dbe30)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/os/user/lookup.go:36 +0x70 fp=0xc0001dbde0 sp=0xc0001dbd90 pc=0x5020b0
github.com/docker/docker/pkg/chrootarchive.init.0()
        /home/travis/gopath/pkg/mod/github.com/docker/docker@v1.4.2-0.20200227233006-38f52c9fec82/pkg/chrootarchive/archive.go:19 +0x36 fp=0xc0001dbe40 sp=0xc0001dbde0 pc=0xc56236
runtime.doInit(0x1bf50c0)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/runtime/proc.go:5222 +0x8a fp=0xc0001dbe70 sp=0xc0001dbe40 pc=0x43d32a
runtime.doInit(0x1bf3e60)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/runtime/proc.go:5217 +0x57 fp=0xc0001dbea0 sp=0xc0001dbe70 pc=0x43d2f7
runtime.doInit(0x1bfbbe0)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/runtime/proc.go:5217 +0x57 fp=0xc0001dbed0 sp=0xc0001dbea0 pc=0x43d2f7
runtime.doInit(0x1bfbf60)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/runtime/proc.go:5217 +0x57 fp=0xc0001dbf00 sp=0xc0001dbed0 pc=0x43d2f7
runtime.doInit(0x1bfdc60)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/runtime/proc.go:5217 +0x57 fp=0xc0001dbf30 sp=0xc0001dbf00 pc=0x43d2f7
runtime.doInit(0x1bfb700)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/runtime/proc.go:5217 +0x57 fp=0xc0001dbf60 sp=0xc0001dbf30 pc=0x43d2f7
runtime.main()
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/runtime/proc.go:190 +0x1da fp=0xc0001dbfe0 sp=0xc0001dbf60 pc=0x430f3a
runtime.goexit()
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0001dbfe8 sp=0xc0001dbfe0 pc=0x45ca91

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/os/signal/signal_unix.go:29 +0x41
```

**Comment by rsdmse** [comment]
I see the exact same error in Ubuntu 20.04 in WSL2.

**Comment by tvvignesh** [comment]
Yup. Same error on my end as well 😟

<img width="686" alt="Capture" src="https://user-images.githubusercontent.com/1165845/95496604-b16bcb80-09be-11eb-91d4-80bcc313d437.png">

**Comment by aphsa** [comment]
**Fails in Ubuntu 18.04.5 LTS**

`fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x34 pc=0x7f655e985dc2]

runtime stack:
runtime.throw(0x116b440, 0x2a)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/runtime/signal_unix.go:378 +0x47c

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xdea640, 0xc0001c5b90, 0xc0000b8948)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/runtime/cgocall.go:128 +0x5b fp=0xc0001c5b60 sp=0xc0001c5b28 pc=0x403d0b
os/user._Cfunc_mygetpwnam_r(0xc00038d7e8, 0xc0003d4720, 0x3b7a070, 0x400, 0xc0000b8948, 0x0)
        _cgo_gotypes.go:156 +0x4d fp=0xc0001c5b90 sp=0xc0001c5b60 pc=0x5026fd
os/user.lookupUser.func1.1(0xc00038d7e8, 0x7, 0x7, 0xc0003d4720, 0xc000428c20, 0xc0000b8948, 0xc0001c5c40)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/os/user/cgo_lookup_unix.go:70 +0x15f fp=0xc0001c5be0 sp=0xc0001c5b90 pc=0x50469f
os/user.lookupUser.func1(0x102e7e0)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/os/user/cgo_lookup_unix.go:70 +0x57 fp=0xc0001c5c28 sp=0xc0001c5be0 pc=0x504747
os/user.retryWithBuffer(0xc000428c20, 0xc0001c5d48, 0x6, 0xc00038d7e8)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/os/user/cgo_lookup_unix.go:251 +0x3b fp=0xc0001c5c80 sp=0xc0001c5c28 pc=0x503c0b
os/user.lookupUser(0x11418cd, 0x6, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/os/user/cgo_lookup_unix.go:61 +0x1c9 fp=0xc0001c5d90 sp=0xc0001c5c80 pc=0x502cb9
os/user.Lookup(0x11418cd, 0x6, 0xc561c2, 0xc0003d46c0, 0xc0001c5e30)
        /home/travis/.gimme/versions/go1.13.10.linux.amd64/src/os/user/lookup.go:36 +0x70 fp=0xc0001c5de0 sp=0xc0001c5d90 pc=0x5020b0
github.com/docker/docker/pkg/chrootarchive.init.0()`

**Comment by apapsch** [comment]
Cleaning house.
