### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by tlawrie** [genuinetools/img#309]
Hi. Any chance we could get a new release both on GitHub releases but also the APK repositories? there have been a lot of changes since 5.10 including cache support and a new version would be appreciated.

**Comment by oxr463** [comment]
The alpine package follows the upstream releases here on Github. Once a new release has been created, then the package will be bumped.

**Comment by tlawrie** [comment]
Ah ok. How do we get a new GitHub release?

**Comment by oxr463** [comment]
> Ah ok. How do we get a new GitHub release?

kindly ping the maintainers :)

**Comment by tlawrie** [comment]
Hey @jessfraz @AkihiroSuda any chance we could get a new github release with the latest updates?

**Comment by jessfraz** [comment]
pushed a new tag here: https://github.com/genuinetools/img/releases/tag/v0.5.11 release is automated and will be uploaded shortly

**Comment by tlawrie** [comment]
Thank you @jessfraz!
