### ISSUE TITLE
At this stage, what is the difference between img and buildkit aside from the frontend?

### ISSUE THREAD

**Issue by cmamigonian** [genuinetools/img#311]
Apologies if this isn't the right forum to ask this, but I'm curious what the difference is between the two tools today other than the frontend.  I've tried to read up on the background online as much as I can but haven't absorbed what that difference is as of today.

**Comment by AkihiroSuda** [comment]
Same except CLI. The upstream BuildKit is more active.

**Comment by cmamigonian** [comment]
Got it, figured as much.  Thank you!
