### ISSUE TITLE
spec: failed to generate spec: no command specified

### ISSUE THREAD

**Issue by tech-about** [genuinetools/img#341]
i use img in gitlab ci pipline in kubernetes, to tag the img and push it to prod, but after tag,  the image seems is broken, i open the --debug but without any warning, how do i fix this ?

**Comment by tech-about** [comment]
i use jib to build the image, ant tag it with img, it seems that meet with some conflict, close this.

**Comment by ulm0** [comment]
i'm facing the exact same issue, mirrored some images from docker hub to gitlab registry using img, and running the images in k8s say `spec: failed to generate spec: no command specified`
