### ISSUE TITLE
Proposal: embed our forked runc to `img` binary (or download it on first run)

### ISSUE THREAD

**Issue by AkihiroSuda** [genuinetools/img#69]
- Plan A: embed `runc` binary to `img` binary
- Plan B: download `runc` binary on first run

**Comment by jessfraz** [comment]
ooo yeah I like A, single static binary :D

**Comment by ehotinger** [comment]
@AkihiroSuda what's the situation for getting that PR merged upstream, are the folks still on vacation? Maybe we can bump that thread again and get some love, it'd be nice to not have the forked version at all.
