### ISSUE TITLE
Failure on copying files into the container. Golang unmarshal error

### ISSUE THREAD

**Issue by bpinske** [genuinetools/img#80]
```
img version                       
img:
 version     : v0.3.0
 git hash    : f9fff83
 go version  : go1.10
 go compiler : gc
 platform    : linux/amd64
```
Line of my dockerfile that img is failing on.

`COPY deploy.sh /deploy.sh
`
Error
`RUN [copy /src-0 /dest/]
--->
json: cannot unmarshal object into Go value of type []string
<--- 9s7u262uf7w4pcee1wy9x6p01 1 <nil>`

**Comment by jessfraz** [comment]
this should work with the latest version but let me know if otherwise
