### ISSUE TITLE
Add support to insecure registry

### ISSUE THREAD

**Issue by guilhermebr** [genuinetools/img#85]
Missing an option to push to an insecure registry.

It's common  for development and integration tests

Log:

`time="2018-05-14T18:59:03Z" level=info msg="pushing layers"
exporting the image 10.200.10.1:5000/tsuru/go:latest failed: failed to do request: Head https://10.200.10.1:5000/v2/tsuru/go/blobs/sha256:a440082623eba20362e20fea387de304e5fe1d6cce355e7189e39ed7d79fdc07: http: server gave HTTP response to HTTPS client`

**Comment by nogoegst** [comment]
Personally I think it's better to spin up TLS at the registry and add an option like `--insecure-skip-verify` or something to `img`.

**Comment by ChaosEternal** [comment]
And also need to add a method to trust customized ca-certs, to support private, ssl-enabled registry.
both pull and push need that.

**Comment by nogoegst** [comment]
@ChaosEternal, not really if you do trust any cert (with `--tls-insecure-skip-verify`).

btw, it seems that this issue should be closed already?
